on: [push]

permissions:
  contents: write

jobs:
  publish-graph: # Changed job name for clarity
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4 # Use v4, it's the latest

      - name: Run Logseq Publish SPA
        # Call your forked action and provide the necessary inputs
        uses: git-165/publish-spa:modified_feat_db
        with:
          # THIS IS THE CRITICAL FIX:
          # Tell the action to build the 'feat/db' branch of logseq/logseq
          version: 'feat/db'
          
          # These inputs are also used, but their defaults are okay.
          # It's good practice to be explicit anyway.
          graph-directory: '.'
          output-directory: 'www'
          theme-mode: 'light'
          accent-color: 'blue'

      - name: Add a .nojekyll file
        run: touch ./www/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www