on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Logseq Publish SPA
      uses: logseq/publish-spa@v0.3.1
      with:
        graph-directory: . # default is .
        output-directory: www # default is www
        version: 0.10.9 # default is 0.10.6
        theme-mode: light # optional, default is light
        accent-color: blue # optional, default is blue
